<?php

$theGamesDbMirror = require __DIR__.'/thegamesdb_mirror.php';

return [
    'providers' => [
        'nexarda' => [
            'label' => 'NEXARDA Aggregator',
            'class' => App\Services\PriceIngestion\Providers\NexardaProvider::class,
            'queue' => 'fetch',
            'rate_limit_per_minute' => 45,
            'regions' => ['US', 'GB', 'EU'],
            'enabled' => true,
            'options' => [
                // Allow either NEXARDA_API_KEY or CATALOGUE_NEXARDA_API_KEY
                'api_key' => env('NEXARDA_API_KEY', env('CATALOGUE_NEXARDA_API_KEY')),
                'base_url' => env('NEXARDA_BASE_URL', 'https://www.nexarda.com/api/v3'),
                'timeout' => env('NEXARDA_PRICING_TIMEOUT', 15),
                'default_regions' => [
                    ['currency' => 'USD', 'region_code' => 'US', 'store_id' => 'nexarda_usd'],
                    ['currency' => 'GBP', 'region_code' => 'GB', 'store_id' => 'nexarda_gbp'],
                    ['currency' => 'EUR', 'region_code' => 'EU', 'store_id' => 'nexarda_eur'],
                ],
                'products' => [
                    [
                        'id' => 2781,
                        'type' => 'game',
                        'title' => 'Six Days in Fallujah',
                        'slug' => 'six-days-in-fallujah',
                        'platform' => 'PC',
                        'category' => 'Game',
                        'regions' => [
                            ['currency' => 'USD', 'region_code' => 'US'],
                            ['currency' => 'GBP', 'region_code' => 'GB'],
                        ],
                    ],
                    [
                        'id' => 101,
                        'type' => 'game',
                        'title' => 'Dark Souls Remastered',
                        'slug' => 'dark-souls-remastered',
                        'platform' => 'PC',
                        'category' => 'Game',
                        'regions' => [
                            ['currency' => 'USD', 'region_code' => 'US'],
                            ['currency' => 'EUR', 'region_code' => 'EU'],
                        ],
                    ],
                ],
                'store_map' => [
                    'Eneba' => [
                        'USD' => ['store_id' => 'nexarda_eneba_usd', 'region_code' => 'US'],
                        'GBP' => ['store_id' => 'nexarda_eneba_gbp', 'region_code' => 'GB'],
                        'EUR' => ['store_id' => 'nexarda_eneba_eur', 'region_code' => 'EU'],
                    ],
                    'Amazon' => [
                        'USD' => ['store_id' => 'nexarda_amazon_usd', 'region_code' => 'US'],
                    ],
                    'ShopTo' => [
                        'GBP' => ['store_id' => 'nexarda_shopto_gbp', 'region_code' => 'GB'],
                    ],
                    'Steam' => [
                        'USD' => ['store_id' => 'nexarda_steam_usd', 'region_code' => 'US'],
                        'GBP' => ['store_id' => 'nexarda_steam_gbp', 'region_code' => 'GB'],
                        'EUR' => ['store_id' => 'nexarda_steam_eur', 'region_code' => 'EU'],
                    ],
                    'GOG' => [
                        'USD' => ['store_id' => 'nexarda_gog_usd', 'region_code' => 'US'],
                        'GBP' => ['store_id' => 'nexarda_gog_gbp', 'region_code' => 'GB'],
                        'EUR' => ['store_id' => 'nexarda_gog_eur', 'region_code' => 'EU'],
                    ],
                    'Green Man Gaming' => [
                        'USD' => ['store_id' => 'nexarda_gmg_usd', 'region_code' => 'US'],
                        'GBP' => ['store_id' => 'nexarda_gmg_gbp', 'region_code' => 'GB'],
                        'EUR' => ['store_id' => 'nexarda_gmg_eur', 'region_code' => 'EU'],
                    ],
                    'Fanatical' => [
                        'USD' => ['store_id' => 'nexarda_fanatical_usd', 'region_code' => 'US'],
                        'GBP' => ['store_id' => 'nexarda_fanatical_gbp', 'region_code' => 'GB'],
                        'EUR' => ['store_id' => 'nexarda_fanatical_eur', 'region_code' => 'EU'],
                    ],
                    'Humble Bundle' => [
                        'USD' => ['store_id' => 'nexarda_humble_usd', 'region_code' => 'US'],
                        'GBP' => ['store_id' => 'nexarda_humble_gbp', 'region_code' => 'GB'],
                        'EUR' => ['store_id' => 'nexarda_humble_eur', 'region_code' => 'EU'],
                    ],
                    'CDKeys' => [
                        'USD' => ['store_id' => 'nexarda_cdkeys_usd', 'region_code' => 'US'],
                        'GBP' => ['store_id' => 'nexarda_cdkeys_gbp', 'region_code' => 'GB'],
                        'EUR' => ['store_id' => 'nexarda_cdkeys_eur', 'region_code' => 'EU'],
                    ],
                    'GAMIVO' => [
                        'USD' => ['store_id' => 'nexarda_gamivo_usd', 'region_code' => 'US'],
                        'GBP' => ['store_id' => 'nexarda_gamivo_gbp', 'region_code' => 'GB'],
                        'EUR' => ['store_id' => 'nexarda_gamivo_eur', 'region_code' => 'EU'],
                    ],
                    'Kinguin' => [
                        'USD' => ['store_id' => 'nexarda_kinguin_usd', 'region_code' => 'US'],
                        'GBP' => ['store_id' => 'nexarda_kinguin_gbp', 'region_code' => 'GB'],
                        'EUR' => ['store_id' => 'nexarda_kinguin_eur', 'region_code' => 'EU'],
                    ],
                    'Instant Gaming' => [
                        'USD' => ['store_id' => 'nexarda_instantgaming_usd', 'region_code' => 'US'],
                        'GBP' => ['store_id' => 'nexarda_instantgaming_gbp', 'region_code' => 'GB'],
                        'EUR' => ['store_id' => 'nexarda_instantgaming_eur', 'region_code' => 'EU'],
                    ],
                    'Gamesplanet' => [
                        'USD' => ['store_id' => 'nexarda_gamesplanet_usd', 'region_code' => 'US'],
                        'GBP' => ['store_id' => 'nexarda_gamesplanet_gbp', 'region_code' => 'GB'],
                        'EUR' => ['store_id' => 'nexarda_gamesplanet_eur', 'region_code' => 'EU'],
                    ],
                    'Epic Games Store' => [
                        'USD' => ['store_id' => 'nexarda_epic_usd', 'region_code' => 'US'],
                        'GBP' => ['store_id' => 'nexarda_epic_gbp', 'region_code' => 'GB'],
                        'EUR' => ['store_id' => 'nexarda_epic_eur', 'region_code' => 'EU'],
                    ],
                    'PlayStation Store' => [
                        'USD' => ['store_id' => 'nexarda_ps_usd', 'region_code' => 'US'],
                        'GBP' => ['store_id' => 'nexarda_ps_gbp', 'region_code' => 'GB'],
                        'EUR' => ['store_id' => 'nexarda_ps_eur', 'region_code' => 'EU'],
                    ],
                    'Nintendo eShop' => [
                        'USD' => ['store_id' => 'nexarda_nintendo_usd', 'region_code' => 'US'],
                        'GBP' => ['store_id' => 'nexarda_nintendo_gbp', 'region_code' => 'GB'],
                        'EUR' => ['store_id' => 'nexarda_nintendo_eur', 'region_code' => 'EU'],
                    ],
                    'Microsoft Store' => [
                        'USD' => ['store_id' => 'nexarda_microsoft_usd', 'region_code' => 'US'],
                        'GBP' => ['store_id' => 'nexarda_microsoft_gbp', 'region_code' => 'GB'],
                        'EUR' => ['store_id' => 'nexarda_microsoft_eur', 'region_code' => 'EU'],
                    ],
                    'Best Buy' => [
                        'USD' => ['store_id' => 'nexarda_bestbuy_usd', 'region_code' => 'US'],
                    ],
                    'Walmart' => [
                        'USD' => ['store_id' => 'nexarda_walmart_usd', 'region_code' => 'US'],
                    ],
                    'GameStop' => [
                        'USD' => ['store_id' => 'nexarda_gamestop_usd', 'region_code' => 'US'],
                    ],
                ],
            ],
        ],
        'steam_store' => [
            'label' => 'Steam Store (Stub)',
            'class' => App\Services\PriceIngestion\Providers\SteamStoreProvider::class,
            'queue' => 'fetch',
            'rate_limit_per_minute' => 30,
            'regions' => [
                'US',
                'CA',
                'GB',
                'DE',
                'FR',
                'IT',
                'ES',
                'NL',
                'SE',
                'PL',
                'AU',
                'NZ',
                'JP',
                'KR',
                'SG',
                'HK',
                'TW',
                'BR',
                'MX',
                'ZA',
            ],
            'enabled' => false,
            'options' => [
                'apps' => [],
                'regions' => [
                    'US',
                    'CA',
                    'GB',
                    'DE',
                    'FR',
                    'IT',
                    'ES',
                    'NL',
                    'SE',
                    'PL',
                    'AU',
                    'NZ',
                    'JP',
                    'KR',
                    'SG',
                    'HK',
                    'TW',
                    'BR',
                    'MX',
                    'ZA',
                ],
                'currencies' => [
                    'USD',
                    'CAD',
                    'GBP',
                    'EUR',
                    'AUD',
                    'NZD',
                    'JPY',
                    'KRW',
                    'SGD',
                    'HKD',
                    'TWD',
                    'BRL',
                    'MXN',
                    'ZAR',
                ],
            ],
        ],
        'itad' => [
            'label' => 'IsThereAnyDeal',
            'class' => App\Services\PriceIngestion\Providers\IsThereAnyDealProvider::class,
            'queue' => 'fetch',
            'rate_limit_per_minute' => 60,
            'regions' => ['US', 'GB', 'EU', 'CA', 'AU'],
            'enabled' => env('ITAD_ENABLED', true),
            'options' => [
                'api_key' => env('ITAD_API_KEY'),
                'default_regions' => [
                    ['currency' => 'USD', 'country' => 'us', 'region_code' => 'US'],
                    ['currency' => 'GBP', 'country' => 'gb', 'region_code' => 'GB'],
                    ['currency' => 'EUR', 'country' => 'de', 'region_code' => 'DE'],
                ],
                'requests' => [
                    [
                        'plain' => 'starfield',
                        'product' => [
                            'title' => 'Starfield',
                            'slug' => 'starfield',
                            'platform' => 'PC',
                            'category' => 'Game',
                        ],
                    ],
                    [
                        'title' => 'Baldur\'s Gate 3',
                        'product' => [
                            'title' => 'Baldur\'s Gate 3',
                            'slug' => 'baldurs-gate-3',
                            'platform' => 'PC',
                            'category' => 'Game',
                        ],
                    ],
                    [
                        'title' => 'Hades II',
                        'product' => [
                            'title' => 'Hades II',
                            'slug' => 'hades-ii',
                            'platform' => 'PC',
                            'category' => 'Game',
                        ],
                        'regions' => [
                            ['currency' => 'USD', 'country' => 'us', 'region_code' => 'US'],
                            ['currency' => 'CAD', 'country' => 'ca', 'region_code' => 'CA'],
                        ],
                    ],
                ],
                'store_map' => [
                    'steam' => [
                        'USD' => ['store_id' => 'itad_steam_usd', 'region_code' => 'US'],
                        'GBP' => ['store_id' => 'itad_steam_gbp', 'region_code' => 'GB'],
                        'EUR' => ['store_id' => 'itad_steam_eur', 'region_code' => 'DE'],
                    ],
                    'humblestore' => [
                        'USD' => ['store_id' => 'itad_humble_usd', 'region_code' => 'US'],
                    ],
                    'gog' => [
                        'USD' => ['store_id' => 'itad_gog_usd', 'region_code' => 'US'],
                        'GBP' => ['store_id' => 'itad_gog_gbp', 'region_code' => 'GB'],
                        'EUR' => ['store_id' => 'itad_gog_eur', 'region_code' => 'DE'],
                    ],
                    'fanatical' => [
                        'USD' => ['store_id' => 'itad_fanatical_usd', 'region_code' => 'US'],
                        'GBP' => ['store_id' => 'itad_fanatical_gbp', 'region_code' => 'GB'],
                        'EUR' => ['store_id' => 'itad_fanatical_eur', 'region_code' => 'DE'],
                    ],
                    'greenmangaming' => [
                        'USD' => ['store_id' => 'itad_gmg_usd', 'region_code' => 'US'],
                        'GBP' => ['store_id' => 'itad_gmg_gbp', 'region_code' => 'GB'],
                        'EUR' => ['store_id' => 'itad_gmg_eur', 'region_code' => 'DE'],
                    ],
                    'epic' => [
                        'USD' => ['store_id' => 'itad_epic_usd', 'region_code' => 'US'],
                        'GBP' => ['store_id' => 'itad_epic_gbp', 'region_code' => 'GB'],
                        'EUR' => ['store_id' => 'itad_epic_eur', 'region_code' => 'DE'],
                    ],
                    'gamersgate' => [
                        'USD' => ['store_id' => 'itad_gamersgate_usd', 'region_code' => 'US'],
                        'GBP' => ['store_id' => 'itad_gamersgate_gbp', 'region_code' => 'GB'],
                        'EUR' => ['store_id' => 'itad_gamersgate_eur', 'region_code' => 'DE'],
                    ],
                    'indiegala' => [
                        'USD' => ['store_id' => 'itad_indiegala_usd', 'region_code' => 'US'],
                        'EUR' => ['store_id' => 'itad_indiegala_eur', 'region_code' => 'DE'],
                    ],
                    'voidu' => [
                        'USD' => ['store_id' => 'itad_voidu_usd', 'region_code' => 'US'],
                        'EUR' => ['store_id' => 'itad_voidu_eur', 'region_code' => 'DE'],
                    ],
                    'wingamestore' => [
                        'USD' => ['store_id' => 'itad_wgs_usd', 'region_code' => 'US'],
                    ],
                    'gamebillet' => [
                        'USD' => ['store_id' => 'itad_gamebillet_usd', 'region_code' => 'US'],
                        'EUR' => ['store_id' => 'itad_gamebillet_eur', 'region_code' => 'DE'],
                    ],
                    'dlgamer' => [
                        'USD' => ['store_id' => 'itad_dlgamer_usd', 'region_code' => 'US'],
                        'EUR' => ['store_id' => 'itad_dlgamer_eur', 'region_code' => 'DE'],
                    ],
                    'nuuvem' => [
                        'USD' => ['store_id' => 'itad_nuuvem_usd', 'region_code' => 'US'],
                        'BRL' => ['store_id' => 'itad_nuuvem_brl', 'region_code' => 'BR'],
                    ],
                ],
            ],
        ],
        'nintendo_eshop' => [
            'label' => 'Nintendo eShop',
            'class' => App\Services\PriceIngestion\Providers\NintendoEshopProvider::class,
            'queue' => 'fetch',
            'rate_limit_per_minute' => 20,
            'regions' => [
                'US',
                'CA',
                'MX',
                'BR',
                'GB',
                'FR',
                'DE',
                'ES',
                'IT',
                'NL',
                'BE',
                'JP',
                'KR',
                'HK',
                'TW',
                'SG',
                'AU',
                'NZ',
                'ZA',
            ],
            'enabled' => false,
            'options' => [
                'countries' => [
                    'US',
                    'CA',
                    'MX',
                    'BR',
                    'GB',
                    'FR',
                    'DE',
                    'ES',
                    'IT',
                    'NL',
                    'BE',
                    'JP',
                    'KR',
                    'HK',
                    'TW',
                    'SG',
                    'AU',
                    'NZ',
                    'ZA',
                ],
                'languages' => ['en', 'fr', 'de', 'es', 'it', 'pt', 'ja', 'ko', 'zh', 'zh-Hant'],
                'title_ids' => [],
            ],
        ],
        'playstation_store' => [
            'label' => 'PlayStation Store (Stub)',
            'class' => App\Services\PriceIngestion\Providers\PlayStationStoreProvider::class,
            'queue' => 'fetch',
            'rate_limit_per_minute' => 15,
            'regions' => [
                'US',
                'CA',
                'MX',
                'BR',
                'AR',
                'CL',
                'PE',
                'GB',
                'IE',
                'DE',
                'FR',
                'ES',
                'IT',
                'PT',
                'NL',
                'BE',
                'SE',
                'NO',
                'DK',
                'FI',
                'PL',
                'CZ',
                'AE',
                'SA',
                'IN',
                'JP',
                'KR',
                'SG',
                'HK',
                'TW',
                'AU',
                'NZ',
            ],
            'enabled' => false,
            'options' => [
                'locales' => [
                    'en-us',
                    'en-ca',
                    'es-mx',
                    'pt-br',
                    'es-ar',
                    'es-cl',
                    'es-pe',
                    'en-gb',
                    'en-ie',
                    'de-de',
                    'fr-fr',
                    'es-es',
                    'it-it',
                    'pt-pt',
                    'nl-nl',
                    'fr-be',
                    'de-at',
                    'sv-se',
                    'nb-no',
                    'da-dk',
                    'fi-fi',
                    'pl-pl',
                    'cs-cz',
                    'ar-ae',
                    'ar-sa',
                    'en-in',
                    'ja-jp',
                    'ko-kr',
                    'en-sg',
                    'zh-hk',
                    'zh-tw',
                    'en-au',
                    'en-nz',
                ],
                'catalog_queries' => [],
            ],
        ],
        'microsoft_store' => [
            'label' => 'Microsoft/Xbox Store (Stub)',
            'class' => App\Services\PriceIngestion\Providers\MicrosoftStoreProvider::class,
            'queue' => 'fetch',
            'rate_limit_per_minute' => 30,
            'regions' => [
                'US',
                'CA',
                'MX',
                'BR',
                'GB',
                'IE',
                'DE',
                'FR',
                'IT',
                'ES',
                'PT',
                'NL',
                'BE',
                'SE',
                'NO',
                'DK',
                'FI',
                'PL',
                'CZ',
                'JP',
                'KR',
                'CN',
                'HK',
                'TW',
                'SG',
                'AU',
                'NZ',
                'IN',
                'ZA',
                'AE',
                'SA',
            ],
            'enabled' => false,
            'options' => [
                'product_ids' => [],
                'markets' => [
                    'US',
                    'CA',
                    'MX',
                    'BR',
                    'GB',
                    'IE',
                    'DE',
                    'FR',
                    'IT',
                    'ES',
                    'PT',
                    'NL',
                    'BE',
                    'SE',
                    'NO',
                    'DK',
                    'FI',
                    'PL',
                    'CZ',
                    'JP',
                    'KR',
                    'CN',
                    'HK',
                    'TW',
                    'SG',
                    'AU',
                    'NZ',
                    'IN',
                    'ZA',
                    'AE',
                    'SA',
                ],
                'languages' => [
                    'en-US',
                    'en-CA',
                    'es-MX',
                    'pt-BR',
                    'en-GB',
                    'en-IE',
                    'de-DE',
                    'fr-FR',
                    'it-IT',
                    'es-ES',
                    'pt-PT',
                    'nl-NL',
                    'fr-BE',
                    'sv-SE',
                    'nb-NO',
                    'da-DK',
                    'fi-FI',
                    'pl-PL',
                    'cs-CZ',
                    'ja-JP',
                    'ko-KR',
                    'zh-CN',
                    'zh-HK',
                    'zh-TW',
                    'en-SG',
                    'en-AU',
                    'en-NZ',
                    'en-IN',
                    'en-ZA',
                    'ar-AE',
                    'ar-SA',
                ],
            ],
        ],
        'pricecharting' => [
            'label' => 'PriceCharting Secondary Market',
            'class' => App\Services\PriceIngestion\Providers\PriceChartingProvider::class,
            'queue' => 'fetch',
            'rate_limit_per_minute' => 10,
            'regions' => ['US', 'CA', 'GB', 'EU', 'JP', 'AU', 'NZ'],
            'enabled' => true,
            'options' => [
                'token' => env('PRICECHARTING_TOKEN'),
                'catalog' => [
                    [
                        'product_slug' => 'super-mario-bros-switch',
                        'title' => 'Super Mario Bros. Wonder',
                        'platform' => 'Nintendo Switch',
                        'category' => 'Game',
                        'search' => 'Super Mario Bros. Wonder Nintendo Switch',
                    ],
                    [
                        'product_slug' => 'zelda-tears-of-the-kingdom',
                        'title' => 'The Legend of Zelda: Tears of the Kingdom',
                        'platform' => 'Nintendo Switch',
                        'category' => 'Game',
                        'search' => 'Zelda Tears of the Kingdom',
                    ],
                    [
                        'product_slug' => 'playstation-5-console',
                        'title' => 'PlayStation 5 Console',
                        'platform' => 'PlayStation 5',
                        'category' => 'Hardware',
                        'search' => 'PlayStation 5 Console',
                    ],
                    [
                        'product_slug' => 'nintendo-switch-oled-console',
                        'title' => 'Nintendo Switch OLED Model',
                        'platform' => 'Nintendo Switch',
                        'category' => 'Hardware',
                        'search' => 'Nintendo Switch OLED console',
                    ],
                    [
                        'product_slug' => 'xbox-series-x-console',
                        'title' => 'Xbox Series X Console',
                        'platform' => 'Xbox Series X',
                        'category' => 'Hardware',
                        'search' => 'Xbox Series X console',
                    ],
                    [
                        'product_slug' => 'elden-ring-ps5',
                        'title' => 'Elden Ring (PS5)',
                        'platform' => 'PlayStation 5',
                        'category' => 'Game',
                        'search' => 'Elden Ring PlayStation 5',
                    ],
                    [
                        'product_slug' => 'halo-infinite-xbox-series',
                        'title' => 'Halo Infinite',
                        'platform' => 'Xbox Series X',
                        'category' => 'Game',
                        'search' => 'Halo Infinite Xbox Series X',
                    ],
                    [
                        'product_slug' => 'resident-evil-4-remake-ps5',
                        'title' => 'Resident Evil 4 Remake (PS5)',
                        'platform' => 'PlayStation 5',
                        'category' => 'Game',
                        'search' => 'Resident Evil 4 remake PS5',
                    ],
                    [
                        'product_slug' => 'metroid-dread-switch',
                        'title' => 'Metroid Dread',
                        'platform' => 'Nintendo Switch',
                        'category' => 'Game',
                        'search' => 'Metroid Dread Nintendo Switch',
                    ],
                ],
                'store_map' => [
                    'loose' => [
                        'store_id' => 'pricecharting_loose_usd',
                        'region_code' => 'US',
                        'condition_label' => 'Loose',
                        'currency' => 'USD',
                        'channel' => 'secondary_market',
                    ],
                    'complete' => [
                        'store_id' => 'pricecharting_complete_usd',
                        'region_code' => 'US',
                        'condition_label' => 'Complete In Box',
                        'currency' => 'USD',
                        'channel' => 'secondary_market',
                    ],
                    'new' => [
                        'store_id' => 'pricecharting_new_usd',
                        'region_code' => 'US',
                        'condition_label' => 'Factory Sealed',
                        'currency' => 'USD',
                        'channel' => 'retail',
                    ],
                ],
            ],
        ],
        'ebay_browse' => [
            'label' => 'eBay Browse API (Stub)',
            'class' => App\Services\PriceIngestion\Providers\EbayBrowseProvider::class,
            'queue' => 'fetch',
            'rate_limit_per_minute' => 60,
            'regions' => ['US', 'CA', 'GB', 'DE', 'FR', 'IT', 'ES', 'AU', 'NZ', 'JP', 'SG', 'HK'],
            'enabled' => false,
            'options' => [
                'oauth_app_id' => env('EBAY_APP_ID'),
                'category_ids' => [],
                'markets' => ['US', 'CA', 'GB', 'DE', 'FR', 'IT', 'ES', 'AU', 'NZ', 'JP', 'SG', 'HK'],
            ],
        ],
        'thegamesdb' => [
            'label' => 'TheGamesDB Metadata',
            'class' => App\Services\PriceIngestion\Providers\TheGamesDbProvider::class,
            'queue' => 'fetch',
            'rate_limit_per_minute' => 45,
            'regions' => ['GLOBAL'],
            'enabled' => true,
            'options' => [
                'public_key' => env('THEGAMESDB_PUBLIC_KEY'),
                'private_key' => env('THEGAMESDB_PRIVATE_KEY'),
                'base_url' => env('THEGAMESDB_BASE_URL', 'https://api.thegamesdb.net/v1'),
                'include' => 'boxart,platforms',
                'fields' => [
                    'overview',
                    'genres',
                    'players',
                    'release_date',
                    'platform',
                    'developer',
                    'publisher',
                ],
                'daily_cap' => 6000,
                'per_minute_cap' => 45,
                'sweep' => [
                    'window_days' => 14,
                    'daily_budget' => 1800,
                    'chunk_size' => 25,
                ],
                'discovery' => [
                    'enabled' => env('THEGAMESDB_DISCOVERY_ENABLED', true),
                    'start_id' => 1,
                    'batch_size' => 200,
                    'requests_per_run' => 10,
                    'use_private_key' => true,
                ],
                'games' => $theGamesDbMirror['games'],
                'platforms' => $theGamesDbMirror['platforms'] ?? [],
            ],
        ],
    ],

    'aggregators' => [
        [
            'key' => 'steam_store',
            'name' => 'Steam Store (unofficial)',
            'kind' => 'digital',
            'platforms' => ['PC'],
            'regions' => ['GLOBAL'],
            'supports_history' => false,
            'auth' => null,
            'rate_limit_note' => 'Undocumented; be polite; cache',
            'docs' => 'Unofficial community references',
            'endpoints' => [
                'app_details' => 'https://store.steampowered.com/api/appdetails?appids={appId}&cc={country}&currency={currency}&filters=price_overview',
            ],
            'notes' => 'Real-time store price per market via cc/currency params.',
        ],
        [
            'key' => 'itad',
            'name' => 'IsThereAnyDeal',
            'kind' => 'digital_aggregator',
            'platforms' => ['PC'],
            'regions' => ['US', 'EU', 'UK', 'JP', 'AU', 'LATAM'],
            'supports_history' => 'historical_low',
            'auth' => 'apiKey',
            'rate_limit_note' => 'Free key; per-interval limits',
            'docs' => 'https://docs.isthereanydeal.com/',
            'endpoints' => [
                'search' => 'https://api.isthereanydeal.com/v02/search/search/?key={apiKey}&q={query}',
                'game_prices' => 'https://api.isthereanydeal.com/v01/game/prices/?key={apiKey}&plains={plain}&country={country}&region={region}',
                'historical_low' => 'https://api.isthereanydeal.com/v01/game/lowest/?key={apiKey}&plains={plain}&country={country}&region={region}',
            ],
            'notes' => 'Great multi-store PC coverage with regions & historical lows.',
        ],
        [
            'key' => 'nintendo_eshop',
            'name' => 'Nintendo eShop (undocumented JSON)',
            'kind' => 'digital',
            'platforms' => ['Nintendo Switch'],
            'regions' => ['US', 'EU', 'JP', 'AU', 'LATAM'],
            'supports_history' => false,
            'auth' => null,
            'rate_limit_note' => 'Undocumented; cache strongly',
            'docs' => 'Community gists/libs',
            'endpoints' => [
                'price_by_title' => 'https://api.ec.nintendo.com/v1/price?country={country}&lang={lang}&ids={titleId}',
            ],
            'notes' => 'Official JSON price endpoint used by the store client.',
        ],
        [
            'key' => 'playstation_store',
            'name' => 'PlayStation Store (scraped/unofficial)',
            'kind' => 'digital',
            'platforms' => ['PlayStation 4', 'PlayStation 5'],
            'regions' => ['US', 'EU', 'JP', 'AU', 'LATAM'],
            'supports_history' => false,
            'auth' => null,
            'rate_limit_note' => 'Scrape/internal APIs; throttle',
            'docs' => 'Community articles/libs',
            'endpoints' => [
                'catalog_search' => 'Unofficial catalog JSON/GraphQL per locale (scrape)',
                'product_pricing' => 'Storefront JSON per SKU & locale (scrape)',
            ],
            'notes' => 'Use community libs or scrape store JSON; store is locale-specific.',
        ],
        [
            'key' => 'microsoft_store',
            'name' => 'Microsoft/Xbox Store (DisplayCatalog)',
            'kind' => 'digital',
            'platforms' => ['Xbox', 'PC (Microsoft Store)'],
            'regions' => ['US', 'EU', 'JP', 'AU', 'LATAM'],
            'supports_history' => false,
            'auth' => null,
            'rate_limit_note' => 'Undocumented public endpoint; be polite',
            'docs' => 'Community references',
            'endpoints' => [
                'products' => 'https://displaycatalog.mp.microsoft.com/v7.0/products?bigIds={idsCsv}&market={market}&languages={lang}&MS-CV=DGU1mcuYo0WMMp+F.1',
            ],
            'notes' => 'Returns price & availability per market for product IDs.',
        ],
        [
            'key' => 'pricecharting',
            'name' => 'PriceCharting',
            'kind' => 'physical_market_index',
            'platforms' => ['Retro', 'Legacy', 'Modern Physical'],
            'regions' => ['US', 'EU', 'JP'],
            'supports_history' => 'trend_series',
            'auth' => 'apiToken',
            'rate_limit_note' => 'Free token; daily-friendly',
            'docs' => 'https://www.pricecharting.com/api-documentation',
            'endpoints' => [
                'search' => 'https://www.pricecharting.com/api/products?t={token}&q={query}',
                'product' => 'https://www.pricecharting.com/api/product?t={token}&id={productId}',
            ],
            'notes' => 'Current prices (loose/complete/new) and historic trend.',
        ],
        [
            'key' => 'ebay_browse',
            'name' => 'eBay Browse API',
            'kind' => 'marketplace_listings',
            'platforms' => ['All'],
            'regions' => ['GLOBAL'],
            'supports_history' => 'sold_items_query',
            'auth' => 'oauth',
            'rate_limit_note' => 'Generous dev tier; per-app limits',
            'docs' => 'https://developer.ebay.com/api-docs/buy/browse/overview.html',
            'endpoints' => [
                'search' => 'https://api.ebay.com/buy/browse/v1/item_summary/search?q={query}&filter=categoryIds:{catId},price:[{min}..{max}],deliveryCountry={country}',
                'item' => 'https://api.ebay.com/buy/browse/v1/item/{itemId}',
            ],
            'notes' => 'Returns price, currency, shipping, taxes, seller, condition.',
        ],
        [
            'key' => 'coingecko',
            'name' => 'CoinGecko (for BTC FX)',
            'kind' => 'fx_crypto',
            'platforms' => [],
            'regions' => ['GLOBAL'],
            'supports_history' => 'btc_history',
            'auth' => 'optional_apiKey',
            'rate_limit_note' => 'Free tier, cached 1–5 min',
            'docs' => 'https://docs.coingecko.com/reference/simple-price',
            'endpoints' => [
                'simple_price' => 'https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies={fiatCsv}',
                'history' => 'https://api.coingecko.com/api/v3/coins/bitcoin/market_chart?vs_currency={fiat}&days={days}',
            ],
            'notes' => 'Use for BTC normalization snapshots.',
        ],
        [
            'key' => 'thegamesdb',
            'name' => 'TheGamesDB',
            'kind' => 'metadata_catalog',
            'platforms' => ['Multi-platform'],
            'regions' => ['GLOBAL'],
            'supports_history' => false,
            'auth' => 'apiKey',
            'rate_limit_note' => 'Public key IP-scoped (~1 req/sec). Private key for initial bulk sync.',
            'docs' => 'https://api.thegamesdb.net/',
            'endpoints' => [
                'search' => 'https://api.thegamesdb.net/Games/ByGameName?apikey={key}&name={query}',
                'updates' => 'https://api.thegamesdb.net/Games/Updates?apikey={key}&time={timestamp}',
                'platforms' => 'https://api.thegamesdb.net/Platforms?apikey={key}',
            ],
            'notes' => 'Use private key server-side to seed data, then public key for IP-scoped incremental updates.',
        ],
    ],

    'stores' => [
        '1' => [
            'retailer' => 'Steam',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
        ],
        '7' => [
            'retailer' => 'GOG',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
        ],
        '3' => [
            'retailer' => 'Green Man Gaming',
            'region_code' => 'GB',
            'currency' => 'GBP',
            'tax_inclusive' => true,
        ],
        '24' => [
            'retailer' => 'GameBillet',
            'region_code' => 'CA',
            'currency' => 'CAD',
            'tax_inclusive' => false,
        ],
        'nexarda_usd' => [
            'retailer' => 'NEXARDA Aggregate (US)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
            'metadata' => [
                'source' => 'nexarda',
            ],
        ],
        'nexarda_gbp' => [
            'retailer' => 'NEXARDA Aggregate (UK)',
            'region_code' => 'GB',
            'currency' => 'GBP',
            'tax_inclusive' => true,
            'metadata' => [
                'source' => 'nexarda',
            ],
        ],
        'nexarda_eur' => [
            'retailer' => 'NEXARDA Aggregate (EU)',
            'region_code' => 'EU',
            'currency' => 'EUR',
            'tax_inclusive' => true,
            'metadata' => [
                'source' => 'nexarda',
            ],
        ],
        'nexarda_eneba_usd' => [
            'retailer' => 'Eneba (Via NEXARDA)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
            'metadata' => [
                'source' => 'nexarda',
                'store_name' => 'Eneba',
            ],
        ],
        'nexarda_eneba_gbp' => [
            'retailer' => 'Eneba UK (Via NEXARDA)',
            'region_code' => 'GB',
            'currency' => 'GBP',
            'tax_inclusive' => true,
            'metadata' => [
                'source' => 'nexarda',
                'store_name' => 'Eneba',
            ],
        ],
        'nexarda_eneba_eur' => [
            'retailer' => 'Eneba EU (Via NEXARDA)',
            'region_code' => 'EU',
            'currency' => 'EUR',
            'tax_inclusive' => true,
            'metadata' => [
                'source' => 'nexarda',
                'store_name' => 'Eneba',
            ],
        ],
        'nexarda_amazon_usd' => [
            'retailer' => 'Amazon (Via NEXARDA)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
            'metadata' => [
                'source' => 'nexarda',
                'store_name' => 'Amazon',
            ],
        ],
        'nexarda_shopto_gbp' => [
            'retailer' => 'ShopTo (Via NEXARDA)',
            'region_code' => 'GB',
            'currency' => 'GBP',
            'tax_inclusive' => true,
            'metadata' => [
                'source' => 'nexarda',
                'store_name' => 'ShopTo',
            ],
        ],
        'nexarda_steam_usd' => [
            'retailer' => 'Steam (Via NEXARDA)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Steam'],
        ],
        'nexarda_steam_gbp' => [
            'retailer' => 'Steam UK (Via NEXARDA)',
            'region_code' => 'GB',
            'currency' => 'GBP',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Steam'],
        ],
        'nexarda_steam_eur' => [
            'retailer' => 'Steam EU (Via NEXARDA)',
            'region_code' => 'EU',
            'currency' => 'EUR',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Steam'],
        ],
        'nexarda_gog_usd' => [
            'retailer' => 'GOG (Via NEXARDA)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'GOG'],
        ],
        'nexarda_gog_gbp' => [
            'retailer' => 'GOG UK (Via NEXARDA)',
            'region_code' => 'GB',
            'currency' => 'GBP',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'GOG'],
        ],
        'nexarda_gog_eur' => [
            'retailer' => 'GOG EU (Via NEXARDA)',
            'region_code' => 'EU',
            'currency' => 'EUR',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'GOG'],
        ],
        'nexarda_gmg_usd' => [
            'retailer' => 'Green Man Gaming (Via NEXARDA)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Green Man Gaming'],
        ],
        'nexarda_gmg_gbp' => [
            'retailer' => 'Green Man Gaming UK (Via NEXARDA)',
            'region_code' => 'GB',
            'currency' => 'GBP',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Green Man Gaming'],
        ],
        'nexarda_gmg_eur' => [
            'retailer' => 'Green Man Gaming EU (Via NEXARDA)',
            'region_code' => 'EU',
            'currency' => 'EUR',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Green Man Gaming'],
        ],
        'nexarda_fanatical_usd' => [
            'retailer' => 'Fanatical (Via NEXARDA)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Fanatical'],
        ],
        'nexarda_fanatical_gbp' => [
            'retailer' => 'Fanatical UK (Via NEXARDA)',
            'region_code' => 'GB',
            'currency' => 'GBP',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Fanatical'],
        ],
        'nexarda_fanatical_eur' => [
            'retailer' => 'Fanatical EU (Via NEXARDA)',
            'region_code' => 'EU',
            'currency' => 'EUR',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Fanatical'],
        ],
        'nexarda_humble_usd' => [
            'retailer' => 'Humble Bundle (Via NEXARDA)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Humble Bundle'],
        ],
        'nexarda_humble_gbp' => [
            'retailer' => 'Humble Bundle UK (Via NEXARDA)',
            'region_code' => 'GB',
            'currency' => 'GBP',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Humble Bundle'],
        ],
        'nexarda_humble_eur' => [
            'retailer' => 'Humble Bundle EU (Via NEXARDA)',
            'region_code' => 'EU',
            'currency' => 'EUR',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Humble Bundle'],
        ],
        'nexarda_cdkeys_usd' => [
            'retailer' => 'CDKeys (Via NEXARDA)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'CDKeys'],
        ],
        'nexarda_cdkeys_gbp' => [
            'retailer' => 'CDKeys UK (Via NEXARDA)',
            'region_code' => 'GB',
            'currency' => 'GBP',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'CDKeys'],
        ],
        'nexarda_cdkeys_eur' => [
            'retailer' => 'CDKeys EU (Via NEXARDA)',
            'region_code' => 'EU',
            'currency' => 'EUR',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'CDKeys'],
        ],
        'nexarda_gamivo_usd' => [
            'retailer' => 'GAMIVO (Via NEXARDA)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'GAMIVO'],
        ],
        'nexarda_gamivo_gbp' => [
            'retailer' => 'GAMIVO UK (Via NEXARDA)',
            'region_code' => 'GB',
            'currency' => 'GBP',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'GAMIVO'],
        ],
        'nexarda_gamivo_eur' => [
            'retailer' => 'GAMIVO EU (Via NEXARDA)',
            'region_code' => 'EU',
            'currency' => 'EUR',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'GAMIVO'],
        ],
        'nexarda_kinguin_usd' => [
            'retailer' => 'Kinguin (Via NEXARDA)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => false,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Kinguin'],
        ],
        'nexarda_kinguin_gbp' => [
            'retailer' => 'Kinguin UK (Via NEXARDA)',
            'region_code' => 'GB',
            'currency' => 'GBP',
            'tax_inclusive' => false,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Kinguin'],
        ],
        'nexarda_kinguin_eur' => [
            'retailer' => 'Kinguin EU (Via NEXARDA)',
            'region_code' => 'EU',
            'currency' => 'EUR',
            'tax_inclusive' => false,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Kinguin'],
        ],
        'nexarda_instantgaming_usd' => [
            'retailer' => 'Instant Gaming (Via NEXARDA)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => false,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Instant Gaming'],
        ],
        'nexarda_instantgaming_gbp' => [
            'retailer' => 'Instant Gaming UK (Via NEXARDA)',
            'region_code' => 'GB',
            'currency' => 'GBP',
            'tax_inclusive' => false,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Instant Gaming'],
        ],
        'nexarda_instantgaming_eur' => [
            'retailer' => 'Instant Gaming EU (Via NEXARDA)',
            'region_code' => 'EU',
            'currency' => 'EUR',
            'tax_inclusive' => false,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Instant Gaming'],
        ],
        'nexarda_gamesplanet_usd' => [
            'retailer' => 'Gamesplanet (Via NEXARDA)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Gamesplanet'],
        ],
        'nexarda_gamesplanet_gbp' => [
            'retailer' => 'Gamesplanet UK (Via NEXARDA)',
            'region_code' => 'GB',
            'currency' => 'GBP',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Gamesplanet'],
        ],
        'nexarda_gamesplanet_eur' => [
            'retailer' => 'Gamesplanet EU (Via NEXARDA)',
            'region_code' => 'EU',
            'currency' => 'EUR',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Gamesplanet'],
        ],
        'nexarda_epic_usd' => [
            'retailer' => 'Epic Games Store (Via NEXARDA)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Epic Games Store'],
        ],
        'nexarda_epic_gbp' => [
            'retailer' => 'Epic Games Store UK (Via NEXARDA)',
            'region_code' => 'GB',
            'currency' => 'GBP',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Epic Games Store'],
        ],
        'nexarda_epic_eur' => [
            'retailer' => 'Epic Games Store EU (Via NEXARDA)',
            'region_code' => 'EU',
            'currency' => 'EUR',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Epic Games Store'],
        ],
        'nexarda_ps_usd' => [
            'retailer' => 'PlayStation Store (Via NEXARDA)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'PlayStation Store'],
        ],
        'nexarda_ps_gbp' => [
            'retailer' => 'PlayStation Store UK (Via NEXARDA)',
            'region_code' => 'GB',
            'currency' => 'GBP',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'PlayStation Store'],
        ],
        'nexarda_ps_eur' => [
            'retailer' => 'PlayStation Store EU (Via NEXARDA)',
            'region_code' => 'EU',
            'currency' => 'EUR',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'PlayStation Store'],
        ],
        'nexarda_nintendo_usd' => [
            'retailer' => 'Nintendo eShop (Via NEXARDA)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Nintendo eShop'],
        ],
        'nexarda_nintendo_gbp' => [
            'retailer' => 'Nintendo eShop UK (Via NEXARDA)',
            'region_code' => 'GB',
            'currency' => 'GBP',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Nintendo eShop'],
        ],
        'nexarda_nintendo_eur' => [
            'retailer' => 'Nintendo eShop EU (Via NEXARDA)',
            'region_code' => 'EU',
            'currency' => 'EUR',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Nintendo eShop'],
        ],
        'nexarda_microsoft_usd' => [
            'retailer' => 'Microsoft Store (Via NEXARDA)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Microsoft Store'],
        ],
        'nexarda_microsoft_gbp' => [
            'retailer' => 'Microsoft Store UK (Via NEXARDA)',
            'region_code' => 'GB',
            'currency' => 'GBP',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Microsoft Store'],
        ],
        'nexarda_microsoft_eur' => [
            'retailer' => 'Microsoft Store EU (Via NEXARDA)',
            'region_code' => 'EU',
            'currency' => 'EUR',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Microsoft Store'],
        ],
        'nexarda_bestbuy_usd' => [
            'retailer' => 'Best Buy (Via NEXARDA)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => false,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Best Buy'],
        ],
        'nexarda_walmart_usd' => [
            'retailer' => 'Walmart (Via NEXARDA)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => false,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'Walmart'],
        ],
        'nexarda_gamestop_usd' => [
            'retailer' => 'GameStop (Via NEXARDA)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => false,
            'metadata' => ['source' => 'nexarda', 'store_name' => 'GameStop'],
        ],
        'pricecharting_loose_usd' => [
            'retailer' => 'PriceCharting Loose (US Market)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => false,
            'metadata' => [
                'source' => 'pricecharting',
                'condition' => 'loose',
            ],
        ],
        'pricecharting_complete_usd' => [
            'retailer' => 'PriceCharting Complete-in-Box (US Market)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => false,
            'metadata' => [
                'source' => 'pricecharting',
                'condition' => 'complete',
            ],
        ],
        'pricecharting_new_usd' => [
            'retailer' => 'PriceCharting New (US Market)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => false,
            'metadata' => [
                'source' => 'pricecharting',
                'condition' => 'new',
            ],
        ],
        'itad_steam_usd' => [
            'retailer' => 'Steam (ITAD)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
            'metadata' => [
                'source' => 'itad',
                'store_name' => 'Steam',
            ],
        ],
        'itad_steam_gbp' => [
            'retailer' => 'Steam UK (ITAD)',
            'region_code' => 'GB',
            'currency' => 'GBP',
            'tax_inclusive' => true,
            'metadata' => [
                'source' => 'itad',
                'store_name' => 'Steam',
            ],
        ],
        'itad_steam_eur' => [
            'retailer' => 'Steam EU (ITAD)',
            'region_code' => 'DE',
            'currency' => 'EUR',
            'tax_inclusive' => true,
            'metadata' => [
                'source' => 'itad',
                'store_name' => 'Steam',
            ],
        ],
        'itad_humble_usd' => [
            'retailer' => 'Humble Store (ITAD)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
            'metadata' => [
                'source' => 'itad',
                'store_name' => 'Humble Store',
            ],
        ],
        'itad_gog_usd' => [
            'retailer' => 'GOG (ITAD)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'itad', 'store_name' => 'GOG'],
        ],
        'itad_gog_gbp' => [
            'retailer' => 'GOG UK (ITAD)',
            'region_code' => 'GB',
            'currency' => 'GBP',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'itad', 'store_name' => 'GOG'],
        ],
        'itad_gog_eur' => [
            'retailer' => 'GOG EU (ITAD)',
            'region_code' => 'DE',
            'currency' => 'EUR',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'itad', 'store_name' => 'GOG'],
        ],
        'itad_fanatical_usd' => [
            'retailer' => 'Fanatical (ITAD)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'itad', 'store_name' => 'Fanatical'],
        ],
        'itad_fanatical_gbp' => [
            'retailer' => 'Fanatical UK (ITAD)',
            'region_code' => 'GB',
            'currency' => 'GBP',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'itad', 'store_name' => 'Fanatical'],
        ],
        'itad_fanatical_eur' => [
            'retailer' => 'Fanatical EU (ITAD)',
            'region_code' => 'DE',
            'currency' => 'EUR',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'itad', 'store_name' => 'Fanatical'],
        ],
        'itad_gmg_usd' => [
            'retailer' => 'Green Man Gaming (ITAD)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'itad', 'store_name' => 'Green Man Gaming'],
        ],
        'itad_gmg_gbp' => [
            'retailer' => 'Green Man Gaming UK (ITAD)',
            'region_code' => 'GB',
            'currency' => 'GBP',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'itad', 'store_name' => 'Green Man Gaming'],
        ],
        'itad_gmg_eur' => [
            'retailer' => 'Green Man Gaming EU (ITAD)',
            'region_code' => 'DE',
            'currency' => 'EUR',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'itad', 'store_name' => 'Green Man Gaming'],
        ],
        'itad_epic_usd' => [
            'retailer' => 'Epic Games Store (ITAD)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'itad', 'store_name' => 'Epic Games Store'],
        ],
        'itad_epic_gbp' => [
            'retailer' => 'Epic Games Store UK (ITAD)',
            'region_code' => 'GB',
            'currency' => 'GBP',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'itad', 'store_name' => 'Epic Games Store'],
        ],
        'itad_epic_eur' => [
            'retailer' => 'Epic Games Store EU (ITAD)',
            'region_code' => 'DE',
            'currency' => 'EUR',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'itad', 'store_name' => 'Epic Games Store'],
        ],
        'itad_gamersgate_usd' => [
            'retailer' => 'GamersGate (ITAD)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'itad', 'store_name' => 'GamersGate'],
        ],
        'itad_gamersgate_gbp' => [
            'retailer' => 'GamersGate UK (ITAD)',
            'region_code' => 'GB',
            'currency' => 'GBP',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'itad', 'store_name' => 'GamersGate'],
        ],
        'itad_gamersgate_eur' => [
            'retailer' => 'GamersGate EU (ITAD)',
            'region_code' => 'DE',
            'currency' => 'EUR',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'itad', 'store_name' => 'GamersGate'],
        ],
        'itad_indiegala_usd' => [
            'retailer' => 'IndieGala (ITAD)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'itad', 'store_name' => 'IndieGala'],
        ],
        'itad_indiegala_eur' => [
            'retailer' => 'IndieGala EU (ITAD)',
            'region_code' => 'DE',
            'currency' => 'EUR',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'itad', 'store_name' => 'IndieGala'],
        ],
        'itad_voidu_usd' => [
            'retailer' => 'Voidu (ITAD)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'itad', 'store_name' => 'Voidu'],
        ],
        'itad_voidu_eur' => [
            'retailer' => 'Voidu EU (ITAD)',
            'region_code' => 'DE',
            'currency' => 'EUR',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'itad', 'store_name' => 'Voidu'],
        ],
        'itad_wgs_usd' => [
            'retailer' => 'WinGameStore (ITAD)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'itad', 'store_name' => 'WinGameStore'],
        ],
        'itad_gamebillet_usd' => [
            'retailer' => 'GameBillet (ITAD)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'itad', 'store_name' => 'GameBillet'],
        ],
        'itad_gamebillet_eur' => [
            'retailer' => 'GameBillet EU (ITAD)',
            'region_code' => 'DE',
            'currency' => 'EUR',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'itad', 'store_name' => 'GameBillet'],
        ],
        'itad_dlgamer_usd' => [
            'retailer' => 'DLGamer (ITAD)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'itad', 'store_name' => 'DLGamer'],
        ],
        'itad_dlgamer_eur' => [
            'retailer' => 'DLGamer EU (ITAD)',
            'region_code' => 'DE',
            'currency' => 'EUR',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'itad', 'store_name' => 'DLGamer'],
        ],
        'itad_nuuvem_usd' => [
            'retailer' => 'Nuuvem (ITAD)',
            'region_code' => 'US',
            'currency' => 'USD',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'itad', 'store_name' => 'Nuuvem'],
        ],
        'itad_nuuvem_brl' => [
            'retailer' => 'Nuuvem BR (ITAD)',
            'region_code' => 'BR',
            'currency' => 'BRL',
            'tax_inclusive' => true,
            'metadata' => ['source' => 'itad', 'store_name' => 'Nuuvem'],
        ],
    ],

    'fx' => [
        'pairs' => [
            ['base' => 'USD', 'quote' => 'BTC'],
            ['base' => 'GBP', 'quote' => 'BTC'],
            ['base' => 'CAD', 'quote' => 'BTC'],
            ['base' => 'USD', 'quote' => 'GBP'],
            ['base' => 'USD', 'quote' => 'CAD'],
            ['base' => 'GBP', 'quote' => 'USD'],
            ['base' => 'EUR', 'quote' => 'BTC'],
            ['base' => 'EUR', 'quote' => 'USD'],
            ['base' => 'AUD', 'quote' => 'BTC'],
            ['base' => 'AUD', 'quote' => 'USD'],
            ['base' => 'NZD', 'quote' => 'BTC'],
            ['base' => 'NZD', 'quote' => 'USD'],
            ['base' => 'JPY', 'quote' => 'BTC'],
            ['base' => 'JPY', 'quote' => 'USD'],
            ['base' => 'KRW', 'quote' => 'BTC'],
            ['base' => 'KRW', 'quote' => 'USD'],
            ['base' => 'SGD', 'quote' => 'BTC'],
            ['base' => 'SGD', 'quote' => 'USD'],
            ['base' => 'HKD', 'quote' => 'BTC'],
            ['base' => 'HKD', 'quote' => 'USD'],
            ['base' => 'TWD', 'quote' => 'BTC'],
            ['base' => 'TWD', 'quote' => 'USD'],
            ['base' => 'BRL', 'quote' => 'BTC'],
            ['base' => 'BRL', 'quote' => 'USD'],
            ['base' => 'MXN', 'quote' => 'BTC'],
            ['base' => 'MXN', 'quote' => 'USD'],
            ['base' => 'ZAR', 'quote' => 'BTC'],
            ['base' => 'ZAR', 'quote' => 'USD'],
            ['base' => 'INR', 'quote' => 'BTC'],
            ['base' => 'INR', 'quote' => 'USD'],
            ['base' => 'CNY', 'quote' => 'BTC'],
            ['base' => 'CNY', 'quote' => 'USD'],
            ['base' => 'AED', 'quote' => 'BTC'],
            ['base' => 'AED', 'quote' => 'USD'],
            ['base' => 'SAR', 'quote' => 'BTC'],
            ['base' => 'SAR', 'quote' => 'USD'],
            ['base' => 'RUB', 'quote' => 'BTC'],
            ['base' => 'RUB', 'quote' => 'USD'],
            ['base' => 'NOK', 'quote' => 'BTC'],
            ['base' => 'NOK', 'quote' => 'USD'],
            ['base' => 'SEK', 'quote' => 'BTC'],
            ['base' => 'SEK', 'quote' => 'USD'],
            ['base' => 'DKK', 'quote' => 'BTC'],
            ['base' => 'DKK', 'quote' => 'USD'],
            ['base' => 'PLN', 'quote' => 'BTC'],
            ['base' => 'PLN', 'quote' => 'USD'],
            ['base' => 'CZK', 'quote' => 'BTC'],
            ['base' => 'CZK', 'quote' => 'USD'],
            ['base' => 'ARS', 'quote' => 'BTC'],
            ['base' => 'ARS', 'quote' => 'USD'],
            ['base' => 'CLP', 'quote' => 'BTC'],
            ['base' => 'CLP', 'quote' => 'USD'],
            ['base' => 'PEN', 'quote' => 'BTC'],
            ['base' => 'PEN', 'quote' => 'USD'],
        ],
        'provider' => 'coingecko',
    ],

    'analysis' => [
        'drop_percentage' => 5,
        'window_minutes' => 60,
    ],
];
